### ISSUE TITLE
About the `torch.nn.LSTM`'s parameter batch_first  in the DeepConvLSTM network

### ISSUE THREAD

**Issue by chencjiajy** [mariusbock/dl-for-har#11]
Hi, Thanks for your excellent tutorial about deep learning for Human Activity Recognition, I learned a lot about data preprocessing.
When I read your code in the [notebook](https://github.com/mariusbock/dl-for-har/blob/main/tutorial_notebooks/training.ipynb): training.ipynb. In the Class `DeepConvLSTM`,  you defined it's lstm layer as:
```python
class DeepConvLSTM(nn.Module):
    def __init__(self, config):
        ...
        # define lstm layers
        self.lstm = nn.LSTM(self.nb_filters*self.nb_channels, hidden_size=self.nb_units_lstm, num_layers=self.nb_layers_lstm)
         ...
```
And in the `DeepConvLSTM`'s forward function:
```python
    def forward(self, x):
        # reshape data for convolutions
        x = x.view(-1, 1, self.window_size, self.nb_channels) #(batch_size, 1, window_size,nb_channels)
        
        # apply convolution and the activation function
        .....
        # sets the final sequence length 
        final_seq_len = x.shape[2]
        
        # permute dimensions and reshape for LSTM
        x = x.permute(0, 2, 1, 3)  #(batch_size, final_seq_len, nb_fillters, nb_channels)
        x = x.reshape(-1, final_seq_len, self.nb_filters * self.nb_channels) #(batch_size, final_seq_len, nb_fillters*nb_channels)

        # apply LSTM (note: it has two outputs!)
        x, _ = self.lstm(x)
```
And in torch's [ LSTM layer document](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html) , the input tensor shape is defined as:
<img width="733" alt="WeChatWorkScreenshot_ef33aec2-8661-46f7-a721-d4c44f7b9755" src="https://github.com/user-attachments/assets/88db8ef6-6c3f-4b5f-bc0f-f263496857d4">

So in my understanding, the input of lstm layer's input tensor's shape is (batch_size, final_seq_len, nb_fillters*nb_channels), we need to set `batch_first=True` when we define LSTM layer.

**Comment by mariusbock** [comment]
Hi, thanks for the kind feedback! Please note that the tutorial implements the shallow DeepConvLSTM (see main repository for details).
