### ISSUE TITLE
get dataset

### ISSUE THREAD

**Issue by z929407579** [mariusbock/dl-for-har#2]
when i  use the link (https : //uni-siegen.sciebo.de/s/sMWQ2vJhDzM6sil )or (https : //uni-siegen.sciebo.de/s/WJeddtW3bTGpiSb),the page show that 
![image](https://user-images.githubusercontent.com/71801854/142401333-031a67be-3c4e-4f9a-ac51-c86a1bc74eba.png)
,can you share the dataset to me ?  thank you

**Comment by mariusbock** [comment]
Hi, the links should work now again.
