### ISSUE TITLE
replaceNANValues

### ISSUE THREAD

**Issue by SameerAdavani** [mariusbock/dl-for-har#4]
Hi,

In tutorial_notebooks/preprocessing.ipynb 
import from data_processing.preprocess_data import replaceNaNValues has to be replaced by 
from data_processing.preprocess_data import replace_nan_values. The replace_nan_values is wrongly imported.

**Comment by mariusbock** [comment]
Hi, thanks for pointing this out. It is fixed in the latest commit.
